"""App config. Most values can be overridden via env / .env."""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

ROOT_DIR = Path(__file__).resolve().parent.parent

# --- LLM provider -----------------------------------------------------
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "openai")
CHAT_MODEL = os.getenv("CHAT_MODEL", "gpt-4o-mini")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "text-embedding-3-small")

# --- Vector store -------------------------------------------------------
CHROMA_PERSIST_DIR = os.getenv("CHROMA_PERSIST_DIR", str(ROOT_DIR / "chroma_db"))
CHROMA_COLLECTION = os.getenv("CHROMA_COLLECTION", "support_kb")

# --- Chunking -------------------------------------------------------------
CHUNK_SIZE = 500
CHUNK_OVERLAP = 75

# --- Retrieval ------------------------------------------------------------
TOP_K = 4

# --- Classifier -------------------------------------------------------------
CLASSIFIER_BASE_MODEL = "distilbert-base-uncased"
CLASSIFIER_ADAPTER_DIR = str(ROOT_DIR / "app" / "classifier" / "lora_adapter")
# "urgent" removed for now - it overlaps with the other labels. Retrain if you add it back.
TICKET_CATEGORIES = ["billing", "technical", "account"]

# --- Paths ------------------------------------------------------------------
KB_DIR = ROOT_DIR / "data" / "kb"
TICKETS_PATH = ROOT_DIR / "data" / "tickets" / "sample_tickets.jsonl"
# Generated by scripts/prepare_training_data.py
PUBLIC_TICKETS_PATH = ROOT_DIR / "data" / "tickets" / "public_tickets.jsonl"
EVAL_DATASET_PATH = ROOT_DIR / "app" / "eval" / "eval_dataset.jsonl"


def get_chat_model():
    if LLM_PROVIDER == "openai":
        from langchain_openai import ChatOpenAI
        return ChatOpenAI(model=CHAT_MODEL, temperature=0.2)
    elif LLM_PROVIDER == "anthropic":
        from langchain_anthropic import ChatAnthropic
        return ChatAnthropic(model=CHAT_MODEL, temperature=0.2)
    raise ValueError(f"Unknown LLM_PROVIDER: {LLM_PROVIDER}")


def get_embeddings():
    if LLM_PROVIDER == "openai":
        from langchain_openai import OpenAIEmbeddings
        return OpenAIEmbeddings(model=EMBEDDING_MODEL)
    raise ValueError(f"No embeddings configured for provider: {LLM_PROVIDER}")
